title: NHM training material
description: Training material for linux and accessing HPC resources at the NHM.

remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
