title: NHM Bioinformatics
description: Training material for linux and accessing HPC resources at the NHM.
theme: just-the-docs

url: https://just-the-docs.github.io

plugins:
  - jekyll-github-metadata

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template