title: NHM Bioinformatics
description: Training material for linux and accessing HPC resources at the NHM.
theme: just-the-docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://o-william-white.github.io/nhm_training" # the base hostname & protocol for your site, e.g. http://example.com
repository: o-william-white/nhm_training # for github-metadata

plugins:
  - jekyll-github-metadata

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
